rust: stable
language: rust

script:
  - cargo build 
  - cargo test 

matrix:
  include:
    - os: linux
      env: TARGET=armv7-unknown-linux-gnueabihf
    - os: linux
      env: TARGET=x86_64-unknown-linux-musl
    - os: osx
      env: TARGET=x86_64-apple-darwin
    - os: windows
      env: TARGET=x86_64-pc-windows-msvc

install:
  - rustup target add $TARGET
      
before_deploy:
  - |
    (
    cargo build --release --target $TARGET    
    if [ "$TRAVIS_OS_NAME" = 'windows' ]; then
      cp target/${TARGET}/release/ess_reader.exe ess_reader-${TRAVIS_TAG}-${TARGET}.exe
    else
      cp target/${TARGET}/release/ess_reader ess_reader-${TRAVIS_TAG}-${TARGET}
    fi
    )
    
deploy:
  api_key:
    secure: "..."

  file: ess_reader-${TRAVIS_TAG}-${TARGET}*
  file_glob: true

  on:
    tags: true

  provider: releases
  skip_cleanup: true
  
branches:
  only:
    # Pushes and PR to the master branch
    - master
    # Ruby regex to match tags.
    # Required, or travis won't trigger deploys when a new tag is pushed.
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
    
notifications:
  email:
    on_success: never
